### PR TITLE
Add support for atmega32u4

### PR DESCRIPTION
**Pull request by looi**
See readme for details

Based on https://github.com/VirtusLab/Ariadne-Bootloader/commit/8676a28d426458eb9de2fa1eafb5da00e4c91b60

### CODE REVIEW

**Comment by loathingKernel** [comment]
From a cursory reading, the pull request is very nice and well documented, thank you!

I do not have the ability to test this, as I don't have a Leonardo available, have to tested it enough? Do you think it is ready? If it is I will go ahead and merge it.

Edit: Did you try to include Caterina and you found out about the size problem? I would like to hear more about that since it was in my plans for supporting Leonardo but never had the willingness to dive into that too.

**Comment by looi** [comment]
I've tested uploading sketches over the network on my XBoard Relay, and it seems fine.

The boards.txt change may not be too helpful since arduino IDE won't be able to upload the sketches without the USB support. (Non-USB serial may work, but I haven't tried it.)

Yeah, I made a hacky attempt to include Caterina and it exceeded the 4096 bytes for the bootloader. If you are interested, I can try to share the code.

**Comment by loathingKernel** [comment]
Ok, I am merging this.

I think retaining the option to upload through the hardware serial is a good compromise if someone needs to do it, if it works or not, it can be improved further down the line. 

Yes I would like to see your attempts if it is not much of an inconvenience to upload it, preferably in a separate branch. You can either make a separate PR for it, or notify me here, anything that is convenient.

**Comment by looi** [comment]
You can see my super hacky attempt to include caterina here. Not tested

https://github.com/looi/ariadne-bootloader/commit/e18eb756d0187d17d4c591c3b1dae6b850f3e7d6

**Pull request merged**
